### PR TITLE
[eas-cli] Upgrade packages to SDK 51 release

### PR DESCRIPTION
**Pull request by wschurman**
# Why

Re-implementation of https://github.com/expo/eas-cli/pull/2364.

# How

Re-apply upgrades (updated since then).

# Test Plan

- Run tests (we don't have too much coverage though).
- Manually create an app, configure for build and an update, submit build, submit update.

### CODE REVIEW

**Comment by wschurman** [comment]
* **#2498** <a href="https://app.graphite.dev/github/pr/expo/eas-cli/2498?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @wschurman and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by szdziedzic** [comment]
Thanks!

**Comment by wschurman** [comment]
### Merge activity

* **Aug 19, 12:25 PM EDT**: @wschurman merged this pull request with [Graphite](https://app.graphite.dev/github/pr/expo/eas-cli/2498).

**Comment by wschurman** [comment]
Whoops, will do changelog in follow-up.

**Pull request merged**
