### PR TITLE
[eas-cli] update expo packages

### PR DESCRIPTION
**Pull request by szdziedzic**
# Why

update expo packages to SDK 51 versions

revert https://github.com/expo/eas-cli/pull/2524

# How

update expo packages to SDK 51 versions

# Test Plan

tests

### CODE REVIEW

**Comment by szdziedzic** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/expo/eas-cli/2530?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2530** <a href="https://app.graphite.dev/github/pr/expo/eas-cli/2530?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2529** <a href="https://app.graphite.dev/github/pr/expo/eas-cli/2529?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2528** <a href="https://app.graphite.dev/github/pr/expo/eas-cli/2528?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @szdziedzic and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by radoslawkrzemien — APPROVED** [review]
LGTM once the failing tests are resolved

**Review by wschurman — APPROVED** [review]
Double check test failures before landing.

**Review by khamilowicz — APPROVED** [review]

**Comment by szdziedzic** [comment]
### Merge activity

* **Nov 5, 1:33 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/expo/eas-cli/2530).

**Pull request merged**
