### PR TITLE
Drop support for node <14

### PR DESCRIPTION
**Pull request by dsokal**
# Checklist

- [ ] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary. You can comment this pull request with `/changelog-entry [breaking-change|new-feature|bug-fix|chore] [message]` and CHANGELOG.md will be updated automatically.

# Why

- Node 18 was released last month - https://nodejs.org/en/about/releases/
- Node 12 is not maintained/supported anymore.

# How

- Drop support for Node 12 and 13.
- Run CI jobs on Node 18.
- Update node and yarn in volta config.
- Upgrade `memfs` to the latest (previous version does not work with Node 18).

# Test Plan

CI

### CODE REVIEW

**Comment by dsokal** [comment]
@brentvatne @kbrandwijk Do you think we can safely "just release" this change or we should rather communicate it somehow? 
On one hand, it can break people's workflows if they use Node 12 in CI and install EAS CLI like `yarn add eas-cli` (no version specified). On the other hand, people should avoid installing non-pinned versions of CLI tools. 
I'm leaning towards just releasing it without any prior announcement.

**Review by wkozyra95 — APPROVED** [review]

**Review by brentvatne — APPROVED** [review]
no need to do any additional communication here - we already said in our release notes for sdk 45 that node 12 is no longer supported, and node 13 wasn't in LTS and therefore not supported.

**Comment by brentvatne** [comment]
although - what will the failure mode be here if users are on node 12? ideally we'd let people know that their node version is incompatible when running any cli command.

we do this in expo-cli here: https://github.com/expo/expo-cli/blob/main/packages/expo-cli/bin/expo.js (although this is slightly out of date, given that expo-cli is primarily in maintenance mode as we migrate towards local cli)

**Comment by dsokal** [comment]
AFAIK if you set the `engines` field in package.json then the failure mode is that npm/yarn just won't let you install the package 🙃

**Comment by brentvatne** [comment]
> AFAIK if you set the `engines` field in package.json then the failure mode is that npm/yarn just won't let you install the package 🙃

haha true. in the case of expo-cli we also cared about making it clear to people that we may not support the latest version yet and wanted to provide some context in the message about it - since you can't control the message if you use `engines`

**Pull request merged**
