### PR TITLE
[eas-cli] add `appVersion` runtime policy

### PR DESCRIPTION
**Pull request by wkozyra95**
# Checklist

- [ ] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary. You can comment this pull request with `/changelog-entry [breaking-change|new-feature|bug-fix|chore] [message]` and CHANGELOG.md will be updated automatically.

# Why

Adds support for app version policy.

# How

Just bump config-plugins and config-types.

cc @brentvatne Or maybe we should bump minor versions and update `@expo/config` too?

# Test Plan

### CODE REVIEW

**Review by dsokal — APPROVED** [review]
1. Take a look at the failing test.
2. Add a changelog entry.

**Review by brentvatne — APPROVED** [review]
this looks good. no need to bump @expo/config version here. we can do a new release of the expo package with this change too

**Comment by brentvatne** [comment]
@dsokal - it looks like the failing test happens on jobs that were previously succeeding 🥵 i re-ran our last successful job here https://github.com/expo/eas-cli/runs/7798127585?check_suite_focus=true

**Comment by wkozyra95** [comment]
/changelog-entry new-feature Add `appVersion` runtime policy.

**Pull request merged**
