### PR TITLE
[ENG-9093][eas-cli] Throw if useClassicUpdates is set when the developer is trying to use EAS Update

### PR DESCRIPTION
**Pull request by ide**
Why
---
Fail fast with a clear message if the app config contradicts itself or the developer's behavior.

How
---
Throw if useClassicUpdates is set in the app config and the developer is running an EAS Update-related command or if the app config uses an EAS Update URL.

Test Plan
---
Added a unit test for ensureEASUpdateIsConfiguredAsync

### CODE REVIEW

**Comment by quinlanj** [comment]
How about a middleground between both our PR's where you tell the user their configuration is incompatible and offer to change it for them (ie) `remove `useClassicUpdates` from your app config?`, since the solution is quite straightforward, it will help the user complete their workflow faster.

**Review by khamilowicz — APPROVED** [review]

**Review by szdziedzic — COMMENTED** [review]
The code change looks good to me

Leaving an assessment of whether it can be done better to the others (https://github.com/expo/eas-cli/pull/1915#issuecomment-1615514584)

**Review by brentvatne — APPROVED** [review]
i believe this runs when you run `eas update` (and not just for `eas update:configure`) so this should be good

**Comment by ide** [comment]
@quinlanj I'll look to see if there is a way to remove config options. I'm not sure it is worth it, though, since this affects just one SDK version.

**Comment by ide** [comment]
/changelog-entry [bug-fix] Ensure useClassicUpdates is not set when using EAS Update commands

**Comment by ide** [comment]
Added context-aware prompts that ask the developer if they would like to remove updates.useClassicUpdates. It will not offer to automatically remove the field if the project doesn't use app.json. Confirmed in a test project that the field is actually deleted, not set to false.

Choosing no:
Screenshot 2023-07-04 at 4 57 39 PM

Choosing yes:
Screenshot 2023-07-04 at 4 57 55 PM

With app.config.js instead of app.json:
Screenshot 2023-07-04 at 5 06 26 PM

**Comment by ide** [comment]
/changelog-entry bug-fix Ensure useClassicUpdates is not set when using EAS Update commands

**Review by quinlanj — APPROVED** [review]
thank you!

**Pull request merged**
