### PR TITLE
[eas-cli] Fix entitlements resolution for multiple iOS targets

### PR DESCRIPTION
**Pull request by HarrisHan**
---

**Fixed an issue where extensions were incorrectly retrieving the main app's entitlements instead of their own. Updated the code to use `dependency.name` for fetching the correct entitlements.**

---

### **Why**

In a project with multiple targets (one main app and two extensions), each target has its own `.entitlements` file with specific capabilities. However, the EAS CLI currently retrieves the `.entitlements` file for all targets using the main app's `.entitlements` file, leading to incorrect capability synchronization with Apple. This behavior causes issues when setting up credentials and syncing capabilities for each target, especially for extensions that require different capabilities from the main app.

### **How**

The issue was addressed by modifying the `resolveBareProjectDependenciesAsync` function within `packages/eas-cli/src/project/ios/target.ts`. Specifically, the code was updated to replace `target.name` with `dependency.name` when retrieving the entitlements file:

```typescript
const entitlements = await getNativeTargetEntitlementsAsync(projectDir, {
  targetName: dependency.name, // Updated to use dependency.name instead of target.name
  buildConfiguration,
});
```

This change ensures that each target retrieves the correct `.entitlements` file, allowing for proper capability configuration for the main app and its extensions.

### **Test Plan**

The changes were tested by running `eas credentials` and observing the resolved entitlements for each target. Below are the outputs before and after the fix, along with the key logs that demonstrate the issue and its resolution:

**Before Fix:**

```bash
Resolved application target with dependencies: {
  name: 'MyApp',
  type: 'com.apple.product-type.application',
  signable: true,
  dependencies: [
    {
      name: 'WalletUIExt',
      type: 'com.apple.product-type.app-extension',
      signable: true,
      dependencies: undefined
    },
    {
      name: 'WalletNonUIExt',
      type: 'com.apple.product-type.app-extension',
      signable: true,
      dependencies: undefined
    }
  ]
}

Processing dependency: WalletUIExt
Resolving entitlements for target: 'MyApp' with configuration 'Release'
Constructed entitlements path: /path/to/project/ios/MyApp/MyApp.entitlements
Read entitlements plist: {
  'aps-environment': 'development',
  'com.apple.developer.payment-pass-provisioning': true,
  'com.apple.security.application-groups': [ 'group.com.example.app' ]
}
Resolved entitlements for dependency: {
  'aps-environment': 'development',
  'com.apple.developer.payment-pass-provisioning': true,
  'com.apple.security.application-groups': [ 'group.com.example.app' ]
}

✔ Synced capabilities: Enabled: Push Notifications
✔ Synced capability identifiers: Linked: group.com.example.app

Processing dependency: WalletNonUIExt
Resolving entitlements for target: 'MyApp' with configuration 'Release'
Constructed entitlements path: /path/to/project/ios/MyApp/MyApp.entitlements
Read entitlements plist: {
  'aps-environment': 'development',
  'com.apple.developer.payment-pass-provisioning': true,
  'com.apple.security.application-groups': [ 'group.com.example.app' ]
}
Resolved entitlements for dependency: {
  'aps-environment': 'development',
  'com.apple.developer.payment-pass-provisioning': true,
  'com.apple.security.application-groups': [ 'group.com.example.app' ]
}

✔ Synced capabilities: Enabled: Push Notifications | Disabled: Wallet
✔ Synced capability identifiers: Linked: group.com.example.app
```

**After Fix:**

```bash
Resolved application target with dependencies: {
  name: 'MyApp',
  type: 'com.apple.product-type.application',
  signable: true,
  dependencies: [
    {
      name: 'WalletUIExt',
      type: 'com.apple.product-type.app-extension',
      signable: true,
      dependencies: undefined
    },
    {
      name: 'WalletNonUIExt',
      type: 'com.apple.product-type.app-extension',
      signable: true,
      dependencies: undefined
    }
  ]
}

Processing dependency: WalletUIExt
Resolving entitlements for target: 'WalletUIExt' with configuration 'Release'
Constructed entitlements path: /path/to/project/ios/WalletUIExt/WalletUIExt.entitlements
Read entitlements plist: {
  'com.apple.developer.payment-pass-provisioning': true,
  'com.apple.security.application-groups': [ 'group.com.example.app' ]
}
Resolved entitlements for dependency: {
  'com.apple.developer.payment-pass-provisioning': true,
  'com.apple.security.application-groups': [ 'group.com.example.app' ]
}

✔ Synced capabilities: Disabled: Push Notifications
✔ Synced capability identifiers: Linked: group.com.example.app

Processing dependency: WalletNonUIExt
Resolving entitlements for target: 'WalletNonUIExt' with configuration 'Release'
Constructed entitlements path: /path/to/project/ios/WalletNonUIExt/WalletNonUIExt.entitlements
Read entitlements plist: {
  'com.apple.developer.pass-type-identifiers': [],
  'com.apple.developer.payment-pass-provisioning': true,
  'com.apple.security.application-groups': [ 'group.com.example.app' ]
}
Resolved entitlements for dependency: {
  'com.apple.developer.pass-type-identifiers': [],
  'com.apple.developer.payment-pass-provisioning': true,
  'com.apple.security.application-groups': [ 'group.com.example.app' ]
}

✔ Synced capabilities: Enabled: Wallet | Disabled: Push Notifications
✔ Synced capability identifiers: Linked: group.com.example.app
```

The key logs demonstrate that after the fix, each target correctly synchronizes its own capabilities based on the appropriate `.entitlements` file, ensuring that the configurations for Push Notifications and Wallet are applied as intended.

Reviewers can reproduce the issue by running the `eas credentials` command in a project with multiple targets, observing the resolved entitlements, and verifying that the correct `.entitlements` file is now being used for each target.

---

### CODE REVIEW

**Review by quinlanj — APPROVED** [review]
thanks, lgtm!

**Comment by HarrisHan** [comment]
Hi @szdziedzic 
If there are no further concerns, would it be possible to merge this PR? Once it's merged and released, I'll be able to update `eas-cli` and proceed with packaging and releasing my app.
Thanks!

**Review by szdziedzic — APPROVED** [review]
LGTM as well! Can you edit CHANGELOG.md to add a changelog entry for this PR?

**Comment by HarrisHan** [comment]
> LGTM as well! Can you edit CHANGELOG.md to add a changelog entry for this PR?
I’ve updated the CHANGELOG.md to include the entry for this PR as requested. Let me know if there’s anything else needed before we can proceed with the merge.

**Comment by szdziedzic** [comment]
It should be released as 12.1.1

**Pull request merged**
