### PR TITLE
[ENG-12122][eas-cli] don't prompt users to set push notifications by default if they don't have the `expo-notifications` installed

### PR DESCRIPTION
**Pull request by szdziedzic**
# Why

https://linear.app/expo/issue/ENG-12122/dont-prompt-people-to-set-push-notifications-by-default-if-they-dont

It was noticed that these prompts not always make sense and may be annoying

# How

don't prompt users to set push notifications by default if they don't have the `expo-notifications` installed

# Test Plan

test manually

with `promptToConfigurePushNotifications` not set and `expo-notifications` not installed:
Screenshot 2024-04-24 at 18 26 25

with `promptToConfigurePushNotifications` not set and `expo-notifications` installed:
Screenshot 2024-04-24 at 18 27 38

### CODE REVIEW

**Comment by szdziedzic** [comment]
/changelog-entry chore Don't prompt users to set push notifications by default if they don't have the `expo-notifications` installed

**Comment by brentvatne** [comment]
very reasonable! i requested review from @douglowder and @christopherwalter since they work on notifications

**Comment by szdziedzic** [comment]
awesome, thanks!

**Review by brentvatne — APPROVED** [review]

**Comment by brentvatne** [comment]
btw, we should check the onesignal docs to ensure that this doesn't cause any issues with their instructions

**Pull request merged**
