### PR TITLE
[chore] Enable remaining lint rules and fix lots of bugs

### PR DESCRIPTION
**Pull request by wschurman**
# Why

This is the real PR I wanted to get to: it uses lint to fix a lot of bugs where promises should have been awaited but weren't. This also fixes bugs where a promise was being accidentally used as a boolean rather than the awaited boolean value.

Closes ENG-13213.

# How

Apply rules, fix manually.

# Test Plan

`yarn lint`

### CODE REVIEW

**Comment by wschurman** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/expo/eas-cli/2510?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2510** <a href="https://app.graphite.dev/github/pr/expo/eas-cli/2510?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2509** <a href="https://app.graphite.dev/github/pr/expo/eas-cli/2509?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2508** <a href="https://app.graphite.dev/github/pr/expo/eas-cli/2508?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2507** <a href="https://app.graphite.dev/github/pr/expo/eas-cli/2507?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2505** <a href="https://app.graphite.dev/github/pr/expo/eas-cli/2505?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2506](https://github.com/expo/eas-cli/pull/2506) <a href="https://app.graphite.dev/github/pr/expo/eas-cli/2506?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @wschurman and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by sjchmiela — APPROVED** [review]
lol

**Review by szdziedzic — APPROVED** [review]
Thank you, for fixing these! This is a huge improvement 👏

**Comment by wschurman** [comment]
### Merge activity

* **Aug 21, 12:11 PM EDT**: @wschurman started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/expo/eas-cli/2510).

**Pull request merged**
