### PR TITLE
feat: use versioned cli for export

### PR DESCRIPTION
**Pull request by EvanBacon**
# Checklist

- [x] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary. You can comment this pull request with `/changelog-entry [breaking-change|new-feature|bug-fix|chore] [message]` and CHANGELOG.md will be updated automatically.

# Why

Fix ENG-6079

- Hide warning:
```
 --non-interactive is not supported, use $CI=1 instead
```

# How

- Check if `@expo/cli` is available in the project. Users can disable this behavior with `EXPO_USE_LOCAL_CLI=false`.
- Ideally, we'd have something like this for changing the default script:
```json
{
  "scripts": {
    "build": "expo export"
  }
}
```
- This seems most aligned with [how web frameworks work](https://vercel.com/docs/concepts/deployments/configure-a-build#build-command).

# Test Plan

- `eas update` in a project with the latest CLI, there will be no warning.

### CODE REVIEW

**Comment by EvanBacon** [comment]
/changelog-entry bug-fix skip using `--non-interactive` and `--experimental-bundle` flags when local Expo CLI is installed.

**Review by jonsamp — APPROVED** [review]
Thanks for updating this command. I tested this locally and confirmed that the warning is gone and that publishing works.

**Comment by jonsamp** [comment]
Fix ENG-6079

**Review by wschurman — APPROVED** [review]

**Review by ide — COMMENTED** [review]
On a related note, @jonsamp or @wschurman could you please update https://github.com/expo/custom-expo-updates-server so that the README and anything else in that repo refer to `npx expo export` instead of `expo export --experimental-bundle`? I happened to be helping a company writing their own Expo Updates server earlier today and confirmed that the new local CLI always exports a modern update.

**Pull request merged**
