### PR TITLE
Add ts-node dev dependency to repo to fix running it locally

### PR DESCRIPTION
**Pull request by brentvatne**
# Checklist

- [ ] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary. You can comment this pull request with `/changelog-entry [breaking-change|new-feature|bug-fix|chore] [message]` and CHANGELOG.md will be updated automatically.

# Why

When executing `bin/run` on `main` I see the following:

image

# How

It seems like we are depending on ts-node installed transitively via `eslint-plugin-graphql`:

```
yarn why ts-node
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "ts-node"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "ts-node@9.0.0"
info Reasons this module exists
   - "_project_#eas-cli#eslint-plugin-graphql#graphql-config#@endemolshinegroup#cosmiconfig-typescript-loader" depends on it
   - Hoisted from "_project_#eas-cli#eslint-plugin-graphql#graphql-config#@endemolshinegroup#cosmiconfig-typescript-loader#ts-node"
info Disk size without dependencies: "1.84MB"
info Disk size with unique dependencies: "3.25MB"
info Disk size with transitive dependencies: "4.05MB"
info Number of shared dependencies: 7
✨  Done in 0.30s.
```

This PR adds it as an explicit dev dependency to the repo, and uses a known working version (the latest).

# Test Plan

Pull the PR, run `yarn`, then run `bin/run`. It should work.

### CODE REVIEW

**Comment by brentvatne** [comment]
/changelog-entry chore Add ts-node dev dependency to fix bin/run script

**Review by dsokal — CHANGES_REQUESTED** [review]
`bin/run` is a symlink to `pacakges/eas-cli/bin/run`. I believe the dependency should be installed in `packages/eas-cli` instead.

**Comment by wkozyra95** [comment]
It looks like this also fixes an issue where `bin/run -> ../packages/eas-cli/bin/dev` was using typescript version from project where it was called. I usually used `packages/eas-cli/bin/run` + `yarn watch` for development to avoid that issue.

**Review by wkozyra95 — APPROVED** [review]

**Comment by dsokal** [comment]
Closing in favor of https://github.com/expo/eas-cli/pull/1262

**Pull request closed without merging**
