### PR TITLE
[eas-cli] update expo packages after SDK 51 release

### PR DESCRIPTION
**Pull request by szdziedzic**
# Why

Update packages after SDK 51 release

# How

Update packages after SDK 51 release

# Test Plan

tests

### CODE REVIEW

**Review by sjchmiela — APPROVED** [review]

**Review by wschurman — APPROVED** [review]

**Comment by Laityned** [comment]
Any updates when it is planned to be merged?

**Comment by patryktrojanowski** [comment]
Any update on that? I guess I'm not the only one blocked with upgrading to sdk 51 due to this

**Comment by wschurman** [comment]
@patryktrojanowski - just curious for testing purposes, what bugs are you seeing without this PR that are preventing upgrade to SDK 51? I re-created this PR (https://github.com/expo/eas-cli/pull/2498) and it would be good to have a complete test plan so any info would be appreciated.

**Comment by szdziedzic** [comment]
Closed in favor of https://github.com/expo/eas-cli/pull/2498

**Pull request closed without merging**
