### PR TITLE
[eas-cli] use `GitNoCommitClient` for `eas build:internal` command

### PR DESCRIPTION
**Pull request by szdziedzic**
# Why

We don't want to fail builds when running `eas build:internal` for people who have `requiredCommit: true` and have modified their project files before the `CONFIGURE_PROJECT` build phase is run. We want to always override the `vcsClient` for the `build:internal` command to `GitNoCommitClient`.

# How

While working on it I noticed that resolving the `vcsClient` works correctly when running `getContextAsync` only because it is always specified as a last field in the command `contextDefinition`. If the order was different `getVcsClient` (used in the `vcsClient` field resolver) might have returned an incorrect value because `setVcsClient` is run separately in other places and it might not be well synchronized.

I deleted the `getVcsClient` and `setVcsClient` functions so `getContextAsync` is the only source of `vcsClient`.

I added the `vcsClientOverride` option to the `getContextAsync` function so we can manually override it if needed like in the `build:internal` command case.

# Test Plan

Use a project with uncommitted changes with `requireCommit: true` and run the `build:internal` command.

Before:
Screenshot 2024-03-21 at 08 56 58

After:
Screenshot 2024-03-21 at 08 57 31

Tests

Run the `eas build` command and check that `vcsClient` behaves correctly depending on whether there are any uncommitted changes and `requireCommit` option value.

### CODE REVIEW

**Review by sjchmiela — APPROVED** [review]
Should we use vcsClient from context everywhere and instead override the vcsClient the context uses? Having two ways to get a vcsClient seems strange? When should I use which?

**Comment by sjchmiela** [comment]
Also, once this is released, what will we need to do to get this fixed in Turtle?

**Comment by szdziedzic** [comment]
It will be fixed automatically because we use the npm tags to set which version is used on staging and prod
https://github.com/expo/eas-build/blob/0a3819f36c1244a859c731571116c2f9e6c19112/packages/build-tools/src/common/easBuildInternal.ts#L12-L14

**Comment by szdziedzic** [comment]
>Should we use vcsClient from context everywhere and instead override the vcsClient the context uses? Having two ways to get a vcsClient seems strange? When should I use which?

You should always use the context one unless you know what you are doing and you want to force override something

**Comment by szdziedzic** [comment]
/changelog-entry bug-fix Improve resolving vcsClient as a part of the project context

**Review by wschurman — APPROVED** [review]

**Review by sjchmiela — APPROVED** [review]

**Pull request merged**
