### PR TITLE
[eas-cli] set default build platform to all

### PR DESCRIPTION
**Pull request by giautm**
# Checklist

- [ ] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary. You can comment this pull request with `/changelog-entry [breaking-change|new-feature|bug-fix|chore] [message]` and CHANGELOG.md will be updated automatically.

# Why

Resolve ENG-4624

# How

How did you build this feature or fix this bug and why?

# Test Plan

Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction.

### CODE REVIEW

**Review by kbrandwijk — CHANGES_REQUESTED** [review]
Not a fan of adding this default, especially when usage based limits will be a thing soon, and forgetting to specify kicks of 2 builds. Especially on CI, it's very easy to be explicit about this, and locally you used to get an interactive question.

If we _really_ want to move forward with this change, I would do it for non-interactive mode only, but I'd rather not.

And if this somehow lands anyway, the code for the interactive prompt should be cleaned up.

**Review by wkozyra95 — CHANGES_REQUESTED** [review]
Agree with @kbrandwijk , also there few other problems:
- it would be bad experience for free users because it would block builds for a bit for them if they can run just one concurrent build 
- a problem for us because we would run some unnecessary builds
- some options e.g. `--local` do not allow running builds with option all

**Review by dsokal — COMMENTED** [review]
I think the same as Kim and Wojtek.

**Comment by giautm** [comment]
Thanks for everyone giving the reviews. I will update the GA to mention that `--platform` is a required flag.

**Pull request closed without merging**
