### PR TITLE
[ENG-5836] add --message param to eas build

### PR DESCRIPTION
**Pull request by dsokal**
# Checklist

- [ ] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary. You can comment this pull request with `/changelog-entry [breaking-change|new-feature|bug-fix|chore] [message]` and CHANGELOG.md will be updated automatically.

# Why

We want to allow users to attach messages to builds.

# How

- Add `--message` / `-m` param to `eas build`.
- Add message to metadata.

# Test Plan

I ran `eas build -m "test message"` and checked that the message was saved to metadata.

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]
🙏

**Review by wkozyra95 — APPROVED** [review]

**Comment by dsokal** [comment]
/changelog-entry new-feature Add support for attaching messages to builds.

**Comment by MorenoMdz** [comment]
@dsokal Hey, quick question about this one, the `message` field is not being replicated to the App payload `manifest` yet right? Is something that we could expect to happen or perhaps need a hand putting that change up?

**Comment by brentvatne** [comment]
@MorenoMdz - i believe you are interested in the message param for eas update, right? this pr is about the a message param for `eas build`. we do not add this to the manifest, no.

**Comment by MorenoMdz** [comment]
> @MorenoMdz - i believe you are interested in the message param for eas update, right? this pr is about the a message param for `eas build`. we do not add this to the manifest, no.

Exactly, I'm curious if we could have this message replicated in the manifest extra, this could lead to a few interesting flows in the app

**Pull request merged**
